name: Install libcFMS with scikit-build-core

on: [push, pull_request]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/noaa-gfdl/fms/fms-ci-rocky-gnu:13.2.0
            env:
                PKG_CONFIG_PATH: "/opt/views/view/lib64/pkgconfig:/opt/views/view/lib/pkgconfig:/opt/views/view/share/pkgconfig"
        steps:
        - name: checkout code
          uses: actions/checkout@v4
        - name: Install lsb-release
          run: |
            apt-get update && apt-get install -y lsb-release && apt-get clean all
        - name: Set up Python 3.11
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            cache: 'pip'
        - name: Run pip install
          run: |
            python -m pip install --upgrade pip
            export LIBYAML_ROOT=/opt/view
            pip install .[develop]
        - name: Run tests
          run: cd tests && ./run_tests.sh -o