name: "pyfms unit tests"
on:
  pull_request:

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pyfms_unit_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/fms/fms-ci-rocky-gnu:13.2.0
    steps:
        - name: Checkout out hash that triggered CI
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'

        - name: install packages
          run: |
            bash compile_c_libs.sh

        - name: run tests
          run: |
            pytest -x tests/
