name: "pyfms unit tests"
on: [push, pull_request]

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pyfms_unit_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/fre-cli:miniconda24_gcc14_v2
    steps:
        - name: Checkout out hash that triggered CI
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'

        - name: install packages
          run: |
            dnf install -y diffutils
            pip install -v .[test]
            cat cFMS/FMS/config.log

        - name: run tests
          run: |
            ./run_tests.sh
