name: "pyfms unit tests"
on: [push, pull_request]

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pyfms_unit_tests:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout out hash that triggered CI
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
        - name: Step Python
          uses: actions/setup-python@v4.6.0
          with:
            python-version: '3.11.7'
        - name: Install OpenMPI for gt4py
          run: |
            sudo apt-get install libopenmpi-dev netcdf-bin libnetcdf-dev libnetcdff-dev nco libyaml-dev diffutils
        - name: install packages
          run: |
            pip install .[test]
        - name: run tests
          run: cd tests && tests/run_tests.sh -o